services:
  app:
    build:
      context: .
    image: syyangv/trek:tailscale
    environment:
      - APP_URL=${APP_URL:-https://home-macbook-air.tailcd6e49.ts.net}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-https://home-macbook-air.tailcd6e49.ts.net}
